# Generated by Django 5.1.15 on 2026-03-27 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0061_task_project_file_upload_idx_async"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="unresolved_review_count",
            field=models.IntegerField(
                db_index=True,
                default=0,
                help_text="Number of unresolved annotation reviews in the task",
                verbose_name="unresolved review count",
            ),
        ),
        migrations.CreateModel(
            name="AnnotationReview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Review comment text", verbose_name="review text"
                    ),
                ),
                (
                    "is_resolved",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Whether this review has been resolved by the annotator",
                        verbose_name="is resolved",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                (
                    "annotation",
                    models.ForeignKey(
                        help_text="The annotation being reviewed",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="tasks.annotation",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created the review",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "annotation_review",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["annotation", "is_resolved"],
                        name="annotation__annotat_b7de7d_idx",
                    )
                ],
            },
        ),
    ]
